#pragma once

#include "NativeGameplayTags.h"

/** The spec's exact tag namespaces (§20), plus event/data tags the systems use. */
namespace EnderTags
{
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attacking);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Evading);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Staggered);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Rooted);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Invulnerable);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_HitReact);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_CastLocked);

	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Basic_ThreadLash);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Core_Sever);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Control_Bind);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Area_Unravel);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Defense_WardingSigil);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Ultimate_GrandFracture);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Movement_Evade);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Draught);

	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Bind);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Unravel);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_WardingSigil);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_GrandFracture);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Evade);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Draught);

	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Physical);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Ender);

	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Barrier);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Root);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Slow);

	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Normal);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Elite);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Boss);

	/** SetByCaller magnitudes. */
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Stagger);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_TemporaryMultiplier);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Duration);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Magnitude);

	/** Gameplay events sent by montage notify states (AbilitySystem/Notifies). */
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_AttackWindow_Begin);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_AttackWindow_End);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_CancelWindow_Evade);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_CancelWindow_Skill);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_HitReact);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Death);

	/** Cancel windows are open while these loose tags are present on the owner. */
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Window_Cancel_Evade);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Window_Cancel_Skill);
	ENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Window_Attack);
}
